### ISSUE TITLE
Parent Issue: Functions for investigating networks

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#242]
We should do this sooner than expected, because it's a dependency for the Microbiome Paper.

- [ ] https://github.com/VEuPathDB/plot.data/issues/239
- [ ] make a function to get a node's neighbors
- [ ] implement community detection algorithm. Consider (weighted) stochastic block model ([ex](https://arxiv.org/pdf/1906.12201.pdf)) or possibly `igraph_community_leiden`. tbd.
- [ ] Some global property like core-periphery ness or small worldness ([weighted version](https://www.nature.com/articles/srep22057)).
- [ ] Topological overlap 

Should have some local (based around a node and its direct neighbors), some [mesoscale](https://www.researchgate.net/figure/Scales-of-network-analysis-a-Brain-networks-are-usually-defined-as-collections-of_fig1_345915242), and a few global (though that's probably less important in this context).

**Comment by d-callan** [comment]
today i learned what 'topological overlap' is, and think support for that goes on this list.

**Comment by d-callan** [comment]
also, we maybe get more detail and possibly some links for things like small worldness and mesoscale. im still acquiring vocabulary here....

**Comment by asizemore** [comment]
Good call. Updated the description!

**Comment by asizemore** [comment]
here's another community detection algorithm worth checking out https://iopscience.iop.org/article/10.1088/1367-2630/16/9/093001

**Comment by asizemore** [comment]
also seems like a good time https://www.researchgate.net/figure/Unipartite-versus-bipartite-representations-A-Unipartite-graph-of-a-network-comprised_fig5_277620255
